upstream iam {
    server iam:3001;
}

upstream category {
    server category:3002;
}

upstream inventory {
    server inventory:3003;
}

upstream procurement {
    server procurement:3004;
}

upstream logistics {
    server logistics:3005;
}

upstream rating {
    server rating:3006;
}

upstream fileupload {
    server fileupload:3007;
}

server {
    listen 8000;

    location /api/auth {
        proxy_pass http://iam;
    }

    location /api/public {
        proxy_pass http://iam;
    }

    location /api/tenants {
        proxy_pass http://iam;
    }

    location /api/customers {
        proxy_pass http://iam;
    }

    location /api/admins {
        proxy_pass http://iam;
    }

    location /api/categories {
        proxy_pass http://category;
    }

    location /api/inventory {
        proxy_pass http://inventory;
    }

    location /api/units {
        proxy_pass http://inventory;
    }

    location /api/products {
        proxy_pass http://inventory;
    }

    location /api/orders {
        proxy_pass http://procurement;
    }

    location /api/logistics {
        proxy_pass http://logistics;
    }

    location /api/ratings {
        proxy_pass http://rating;
    }

    location /upload {
        proxy_pass http://fileupload;
    }

    location /files {
        proxy_pass http://fileupload;
    }
}
